name: CI-CD-PRACTICE

on:
  push:
    branches: [main]

env:
  NODE_VERSION: "24"

jobs:
  backend-test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: install dependencies
        run: npm ci

      - name: test lints
        run: npm run lint

      - name: test code
        run: npm run test

      - name: build
        run: npm run build
